// =====================================================================
// Messages shown while descending/loading (the audit is running).
// 300+ entries - players wait 10-15 minutes, so variety is critical.
// Tone: dark, brooding, low fantasy. Despair, dread, isolation, decay.
// =====================================================================
export const DESCENT_MESSAGES = [
  // ── Original ──
  "The air grows thin.",
  "Steel on stone.",
  "Deeper.",
  "No turning back.",
  "Something shifted below.",
  "The walls are wet.",
  "Torch won't last.",
  "Bones underfoot.",
  "The dark thickens.",
  "It knows you're here.",
  "Keep moving.",
  "The stairs have no end.",
  "Cold iron. Cold air.",
  "A sound. Then nothing.",
  "The weight of stone above.",
  "Dripping. Steady. Close.",
  "Your shadow left you.",

  // ── Batch 1: Darkness and descent ──
  "The torch dims without wind.",
  "Dripping. Always dripping.",
  "Cold stone remembers nothing.",
  "Something moved in the dark.",
  "The walls are wet here.",
  "Your breath clouds and fades.",
  "Iron taste on your tongue.",
  "The echo did not return.",
  "Deeper than the roots go.",
  "Bones ground to white dust.",
  "The dark has weight here.",
  "No light from above now.",
  "Silence louder than screaming.",
  "The steps behind you stopped.",
  "Water finds the lowest place.",
  "Rust and rot and stone.",
  "You are not the first.",
  "The ceiling presses down slowly.",
  "Old blood on old iron.",
  "Something breathes in the dark.",
  "Your shadow moves without you.",
  "Walls slick with cold seep.",
  "The air has no memory.",
  "Down is the only direction.",
  "These halls swallowed their builders.",
  "The dark is not empty.",
  "Footsteps fill with standing water.",
  "The cold is awake here.",
  "Nothing grows this deep down.",
  "Wet stone. Faint iron smell.",
  "The dark watches. It waits.",
  "Ribs in the settling dust.",
  "Even your name fades here.",
  "The passage narrows. Always.",
  "There is no morning here.",
  "Fingers wore grooves in stone.",
  "The weight of earth above.",
  "Somewhere, a door closes itself.",
  "Your light is borrowed time.",
  "Moss covers what screamed last.",
  "The stairwell has no bottom.",
  "Black water. Do not drink.",
  "The rot smells like memory.",
  "Something old settled in the walls.",
  "Stone does not forget footsteps.",
  "The dark is older here.",
  "A sound. Then nothing. Then-",
  "The pit goes further down.",
  "Cold hands left these marks.",
  "The flame leans toward nothing.",
  "Hollow sockets in hollow stone.",
  "These halls were not built.",
  "The dark grows thicker below.",
  "Your heartbeat sounds very loud.",
  "Dust from where the ceiling sags.",
  "The water runs toward something.",
  "Iron doors. No handles inside.",
  "The dark has learned patience.",
  "Old stone, older silence.",
  "The passage does not widen.",
  "Something was dragged through here.",
  "Your torch makes shadows move.",
  "The steps are worn smooth.",
  "Not all who descended returned.",
  "The air sits heavy here.",
  "Cracks in stone. Old cracks.",
  "The dark has texture now.",
  "Teeth marks on the doorframe.",
  "The cold enters the bones.",
  "Your reflection is not there.",
  "The tunnel bends away from light.",
  "Water drips through ancient seams.",
  "Whatever lived here left bones.",
  "The dark does not mind waiting.",
  "Stone remembers pressure.",
  "The silence is a sound.",
  "The word means less now.",
  "No wind. No sound. Descend.",

  // ── Batch 2: Scratching, corpses, sealed passages ──
  "Something scratched and went still.",
  "The passage narrows ahead.",
  "Rust and old blood.",
  "A door, sealed from within.",
  "The chains hang empty.",
  "Footsteps that are not yours.",
  "The walls sweat in the cold.",
  "Another corpse faced downward.",
  "Silence after the settling stone.",
  "The smell of turned earth.",
  "Torchlight does not reach the ceiling.",
  "A name carved into the floor.",
  "The stairs continue past the map.",
  "Breathing that is not breathing.",
  "Mud seals the lower passage.",
  "Someone died reaching for the wall.",
  "The echo returns wrong.",
  "Iron rings, no chains attached.",
  "Three doors. Two collapsed.",
  "Wet stone. No water source.",
  "Old smoke stains on the ceiling.",
  "A torch burned down to nothing.",
  "The corridor bends and bends.",
  "Scratching inside the sealed wall.",
  "Roots have broken through the stone.",
  "The cold comes from below.",
  "A pile of discarded tools.",
  "The lantern oil is nearly gone.",
  "Bones arranged with care.",
  "The rot smell thickens here.",
  "Eyes in the dark, or none.",
  "The door opens both ways.",
  "A hand, reaching from rubble.",
  "Something watches from the high ledge.",
  "The floor gives slightly underfoot.",
  "Mold in the shape of fingers.",
  "The passage was sealed from outside.",
  "A belt buckle, no body near.",
  "The stone here is scorched.",
  "Whatever it was, it crawled.",
  "The torch gutters and holds.",
  "A shallow grave, unmarked.",
  "Dust on the inside of the door.",
  "Something soft beneath the gravel.",
  "The ceiling drips black.",
  "An open lock with no chain.",
  "Fingernail marks on the stone.",
  "The corridor ends in earth.",
  "Something left its shell behind.",
  "The dark absorbs the torchlight.",
  "A voice, very far below.",
  "Rubble still warm from collapse.",
  "The smell of iron and sleep.",
  "Another level down. Another still.",
  "The wood of the door is soft.",
  "A shadow that does not move.",
  "The footprints stop mid-corridor.",
  "Teeth marks in the mortar.",
  "The crack in the ceiling widens.",
  "Everything here died slowly.",
  "A pile of coins, untouched.",
  "The dark does not echo.",
  "Dust falls without disturbance.",
  "The walls are closer than before.",
  "An open book, pages rotted blank.",
  "The steps descend without counting.",
  "Something lives in the drain.",
  "A rope, cut near the anchor.",
  "The passage smells of long waiting.",
  "Stone dust settles on the dead.",
  "The door was opened from below.",
  "Nothing moves. Nothing has moved.",

  // ── Batch 3: Forgotten kingdoms, futility ──
  "The walls remember everything.",
  "Something moved ahead.",
  "No one sent you here.",
  "You have forgotten the sun.",
  "This corridor was sealed for reasons.",
  "The mechanism still turns.",
  "Bone dust on the floor.",
  "Something breathed here recently.",
  "The inscription has been scratched out.",
  "There are no exits marked.",
  "The chains are old. The locks are not.",
  "The burial rites were never finished.",
  "Deeper means darker.",
  "The throne room sits empty.",
  "Whatever built this is still here.",
  "The descent continues.",
  "A child's drawing on the wall.",
  "The floor is warm.",
  "These were once streets.",
  "The archive burned from within.",
  "You are below the graves now.",
  "The last cartographer stopped here.",
  "They feared what they worshipped.",
  "The ropes have long since rotted.",
  "The altars face the wrong direction.",
  "Stone wears down. The dark does not.",
  "You count steps. You lose count.",
  "The empire was thorough in its erasure.",
  "The collapse came from below.",
  "The lanterns were deliberately broken.",
  "You follow marks left in desperation.",
  "The dead were stacked, not buried.",
  "This level was not on the map.",
  "The architecture makes no sense.",
  "Whatever they dug for, they found it.",
  "You pass through where others stopped.",
  "The name of this place was removed.",
  "The pillars are compressed ash.",
  "You have been walking for hours.",
  "The shadows do not move with light.",
  "The scripture here is a warning.",
  "The bridge holds. Barely.",
  "The locks were sealed from outside.",
  "The roots have reached this depth.",
  "Nothing decays here. Nothing ends.",
  "The veins in the rock pulse faintly.",
  "A shrine to an unknown grief.",
  "The ceiling has faces in it.",
  "The workers never left.",
  "This chamber was meant to be forgotten.",
  "The last fire was a long time ago.",
  "Whatever they built outlasted them.",
  "You move through a long exhale.",
  "The gears have not stopped turning.",
  "Stone absorbs the sound of steps.",
  "The hunger is manageable. For now.",
  "Whatever bled here, bled long.",
  "These halls were built to confuse.",
  "A figure carved to look away.",
  "The water here is black and still.",
  "You have passed this mark before.",
  "The dark is consistent. You are not.",
  "The floor slopes. You did not notice.",
  "There is no going back up.",

  // ── Batch 5: The Thing Below ──
  "It has no name you could speak.",
  "Something dreamed you into its halls.",
  "The quiet has intent.",
  "It does not need eyes to see.",
  "The stones were its teeth once.",
  "It does not move. It is moved.",
  "Each step feeds it a little.",
  "Old hunger. Slow hunger. Near.",
  "It was a prisoner first.",
  "The dungeon is its skin.",
  "Do not think its true shape.",
  "It learns what you are afraid of.",
  "You hear it through your bones.",
  "It has been waiting patiently.",
  "It pulls without pulling.",
  "The walls lean toward you.",
  "It counts your breaths.",
  "It knows the shape of your face.",
  "The cold moves with a purpose.",
  "Something vast turns over below.",
  "It tastes what the water carries.",
  "You are not interesting to it yet.",
  "The rot obeys a rhythm.",
  "Not all sounds in the dark are sound.",
  "Its children left these marks.",
  "It has been dreaming of daylight.",
  "The walls flex when it exhales.",
  "It was worshipped, then feared, then forgotten.",
  "Stone remembers its first cry.",
  "Something vast holds very still.",
  "It is already inside the room.",
  "The ceiling remembers its weight.",
  "It has no hurry.",
  "You descend into its open mouth.",
  "It stirs only when ignored.",
  "Its hunger shaped this place.",
  "The silence is how it listens.",
  "It cannot leave. It does not need to.",
  "It wears the dark like a coat.",
  "Something below opens its eye.",

  // ── Batch 6: Those Who Came Before ──
  "A pilgrim, hands folded, dead.",
  "They carved a saint, then broke it.",
  "The surveyor's theodolite, rusted shut.",
  "A scholar's satchel, pages gone.",
  "They left a note that says only: wait.",
  "The cartographer wept at this line.",
  "A child's shoe, size of your palm.",
  "The priest took off his collar here.",
  "Their last camp, unburied.",
  "A miner, pickaxe still in hand.",
  "The knight did not finish kneeling.",
  "Two bodies, arms locked.",
  "An explorer's journal, last line unfinished.",
  "The architect's apprentice, alone.",
  "A deserter, facing the wall.",
  "She carved the star over and over.",
  "He died writing a letter home.",
  "Their lantern, wick trimmed neat.",
  "The courier's bag, unopened.",
  "A tax collector, purse untouched.",
  "The surgeon's kit, unused.",
  "A warden, keys still on his belt.",
  "The mason had his hand inside the wall.",
  "A monk, eyes sewn shut.",
  "He tied himself to a stone for weight.",
  "The oracle's teeth in a little cloth.",
  "A gravedigger, no grave finished.",
  "The sculptor, half-fused with his marble.",
  "A cook, spoon still in his hand.",
  "Three pilgrims, one rope.",
  "The bishop's mitre, crushed flat.",
  "A herald, trumpet bent.",
  "The torchbearer fell before the others.",
  "A beggar, robes finer than any king.",
  "Twin skeletons, turned away from each other.",
  "The messenger never delivered the scroll.",
  "A bride, ring still on her bone.",
  "An infant's cradle, far from any home.",
  "The forge-master, tongs clenched in rigor.",
  "A cartwright, no cart to be seen.",

  // ── Batch 7: Inscriptions and Warnings ──
  "\"Turn back\" carved ten times in one wall.",
  "The scripture says: hold your breath.",
  "A warning, worn to braille.",
  "\"Below is below\" repeats on every stone.",
  "The prayer is only a name, written wrong.",
  "Someone scratched: \"we can hear you.\"",
  "The carving reads: it will not be rushed.",
  "A liturgy that loops and loops and loops.",
  "The inscription: \"lamp out at third bell.\"",
  "\"Close the door behind you.\" The door is gone.",
  "The stone reads: five days, then five more.",
  "\"The walls answer if you ask wrong.\"",
  "A list of names, all the same name.",
  "\"Do not touch the water\" in four languages.",
  "The priest carved his last confession here.",
  "A ward carved upside down on purpose.",
  "\"Too late\" on every fifth step.",
  "The threshold says: speak nothing below.",
  "\"Feed the dark\" and nothing else.",
  "A tally mark for every mile. Hundreds.",
  "The inscription runs around the room forever.",
  "The script is old. The ink is not.",
  "A rune scratched over a rune scratched over.",
  "\"My son made it further.\"",
  "The warning has been chiseled away.",
  "A prayer to no god you recognize.",
  "\"Do not sleep here\" inside a bed-sized alcove.",
  "The proverb ends \"...or they will know you.\"",
  "A child wrote: \"tell mother I tried.\"",
  "The sign reads: bring no light.",
  "A crude map, crossed out in red.",
  "\"The dark is owed a debt\" with no source.",
  "The scribe stopped mid-letter.",
  "\"Thirty souls went down. One came back.\"",
  "A list in reverse chronological order.",
  "\"They were here yesterday.\"",
  "The plaque has been turned to face the wall.",
  "A vow pressed in lead, unread.",
  "The decree: this chamber does not exist.",
  "\"You have come too far to turn back.\"",

  // ── Batch 8: The Body in Descent ──
  "Your hands shake and will not stop.",
  "Sweat cools and does not dry.",
  "The taste of copper will not leave.",
  "Your knees remember the last fall.",
  "Blood dries darker than you remember.",
  "The cold finds its way inside your lungs.",
  "Your fingers are numb past feeling.",
  "You have forgotten what sunlight felt like.",
  "The soles of your boots have worn through.",
  "Your ribs remind you of every breath.",
  "The muscles in your back twitch without cause.",
  "Your eyes adjust. Then the dark adjusts.",
  "A headache settles in that will not leave.",
  "You lick cracked lips and taste iron.",
  "Your body insists it has not slept.",
  "The ache in your shoulder is older than the bruise.",
  "You swallow and the sound carries.",
  "Your pulse moves the torchlight.",
  "The wound stopped bleeding hours ago.",
  "Your breath fogs less and less.",
  "A tooth is loose. You cannot say which.",
  "The cramp in your leg comes and goes.",
  "Your teeth chatter and you cannot still them.",
  "Your throat is raw from silence.",
  "The dizziness passes. Returns. Passes.",
  "Your fingers smell of rust and soil.",
  "You hear your own heart and nothing else.",
  "The shiver starts deeper than skin.",
  "Your breath keeps a rhythm you do not set.",
  "The stink of yourself is comforting, then not.",
  "Your eyes water without tears.",
  "The hunger stopped mattering some hours ago.",
  "You walk past the point your body would stop.",
  "The callus on your palm has split.",
  "Your bones feel brittle and close to the surface.",
  "You taste the iron before the blood.",
  "The numbness creeps upward.",
  "You have bitten your cheek raw.",
  "The joint in your hip clicks with each step.",
  "Your lungs complain, then acquiesce.",

  // ── Batch 9: Time and Memory ──
  "You have forgotten which day you entered.",
  "The hour does not exist here.",
  "You counted to ten thousand and stopped.",
  "The name of your home is slipping.",
  "The sun is a rumor you once believed.",
  "You passed that same mark an hour ago.",
  "Or a day ago. Or just now.",
  "The map you drew contradicts itself.",
  "Memory of above feels like someone else's.",
  "You said the word \"sky\" and it sounded wrong.",
  "Yesterday is a concept. Not a fact.",
  "You try to picture grass. It does not come.",
  "The torch is older than your journey.",
  "You find footprints that are your size.",
  "The tally you kept is gone.",
  "Hours here are not hours elsewhere.",
  "You have thought this exact thought before.",
  "The dungeon is older than any story.",
  "You forget the shape of a door.",
  "The last thing you ate was warm.",
  "You remember laughter. You cannot picture it.",
  "Something you loved. You cannot name it.",
  "The last time you were touched feels important.",
  "You have been walking longer than you have lived.",
  "Your reflection shows someone you used to know.",
  "The word for the sky is slipping.",
  "You are not certain of your name.",
  "A memory returns but does not feel yours.",
  "Time here is a texture. Not a direction.",
  "You try to remember being dry.",
  "The surface is a theory, unproven.",
  "You have walked past noon many times.",
  "Your childhood has taken on the color of stone.",
  "You cannot picture a window.",
  "The color green is a guess.",
  "Whatever you were, you are becoming else.",
  "The surface is another country you once heard of.",
  "Time moved sideways here once.",
  "The clock you carried runs backward now.",
  "You tried to sleep. Time declined.",

  // ── Batch 10: Objects Left Behind ──
  "A wedding ring on a bare finger.",
  "A sealed letter, water-swollen.",
  "A child's wooden sword, broken.",
  "A pouch of coins, none of this kingdom.",
  "A wax seal, the crest worn flat.",
  "A music box, lid shut, springs gone.",
  "A rosary with two beads left.",
  "A pipe, tobacco still inside.",
  "A compass pointing down.",
  "A cookbook, pages stained with something red.",
  "A doll with its face turned backward.",
  "A violin, strings all cut.",
  "A pair of spectacles, one lens missing.",
  "A jar of teeth. Human. Not uniform.",
  "A wedding veil, folded with care.",
  "A pocket watch, still ticking.",
  "A bouquet of dried black flowers.",
  "A family portrait, painted over.",
  "A silver bell with its clapper removed.",
  "A signet ring with no stone.",
  "A candle so new the wick is unburnt.",
  "A lantern with no oil, still lit.",
  "A saint's finger in a glass tube.",
  "A bone whistle. Cannot be blown.",
  "A page torn from a book that does not exist.",
  "A mask carved to match your face.",
  "A folded map with no markings.",
  "A sword with no edge and no point.",
  "A heart-shaped locket, empty.",
  "A key that does not fit any lock here.",
  "A dagger sheathed in itself.",
  "A bird cage, door open.",
  "A gambler's dice, weighted.",
  "A child's drawing: sun, house, grave.",
  "A ledger balanced to zero in red.",
  "A thimble large enough for a thumb bone.",
  "A stack of unsigned confessions.",
  "A rope knotted thirty-three times.",
  "A candle stub, wick knotted.",
  "A diary with every entry scratched out but one.",

  // ── Batch 11: Architecture of Malice ──
  "These halls were built to be uneven.",
  "The doorframe is slightly too short.",
  "The corridor narrows by inches you cannot see.",
  "The staircase has one step missing.",
  "The room is not quite square.",
  "The ceiling presses lower the longer you stand.",
  "The mortar between stones is still wet.",
  "The walls curve gently inward.",
  "The floor has a slope you cannot feel.",
  "The pillars lean in agreement.",
  "The archways shrink toward you.",
  "The stones fit without seam or mortar.",
  "The architecture refuses symmetry.",
  "The geometry makes the eye tired.",
  "The walls are carved with pressure marks.",
  "The corridor loops but does not end.",
  "The same room, rotated.",
  "The passage widens only where no one would turn.",
  "The room has corners where corners should not be.",
  "The ceiling has been lowered intentionally.",
  "The doors open inward toward the visitor.",
  "The windows face stone.",
  "The architrave trembles without cause.",
  "The spiral staircase coils counter-clockwise.",
  "The room is larger on the inside.",
  "The walls are thicker than the room allows.",
  "Three archways. Two lead down.",
  "The floor tile pattern repeats wrong.",
  "The hallway bends back on itself.",
  "The stairs descend into water you cannot hear.",
  "Every fifth stone is slightly warmer.",
  "The columns do not support the ceiling.",
  "The mosaics depict the rooms you have not yet seen.",
  "The throne faces the wall.",
  "The antechamber was built to trap sound.",
  "Every door is the same door, reused.",
  "The rooms are arranged as a face.",
  "The stairwell circles a pit older than the stone.",
  "The walls were built around what they hide.",
  "The architect left no signature. Intentionally.",

  // ── Batch 12: Ritual Remnants ──
  "An altar bearing a smaller altar.",
  "Salt poured in a circle, long disturbed.",
  "Candles arranged to spell nothing.",
  "A basin of black water, covered in skin.",
  "An offering of teeth and hair.",
  "The censer swings in still air.",
  "Bells were hung here, then buried.",
  "A font of oil that does not reflect.",
  "Chalk markings under a layer of blood.",
  "The effigy was burned and rebuilt.",
  "A mirror facing the wall.",
  "A book nailed open to one page.",
  "Incense gone to stone.",
  "The prayer mat is soaked through.",
  "A bone knife on a cloth of black.",
  "The circle was drawn from the center outward.",
  "Hair braided and left as offering.",
  "The ritual was interrupted.",
  "Salt and iron in unequal parts.",
  "A bowl of milk, still white, impossibly still.",
  "A garland of eyes, carved from wood.",
  "The candles burned down to black nubs.",
  "A procession was here. Their feet did not touch.",
  "The baptismal font holds old rainwater.",
  "The altar holds a cavity for something missing.",
  "A wax effigy of someone you recognize.",
  "The hymnal opens to the same page.",
  "The pulpit faces away from the pews.",
  "Seven candles. Six burned out.",
  "A processional path worn into stone.",
  "The relic is gone. The reliquary remains.",
  "A mark was made. A greater mark unmade it.",
  "The ritual required a sacrifice unwilling.",
  "The ritual required a sacrifice willing.",
  "The ritual required neither.",
  "A veil. Under it, another veil. Under that, dust.",
  "The brazier holds ash that has not cooled.",
  "The floor is worn smooth by knees.",
  "Vestments hang where a body used to.",
  "Something was invited. Something came.",

  // ── Batch 13: The Dark as Character ──
  "The dark is the only honest thing here.",
  "The dark keeps a ledger.",
  "The dark has no interest in you yet.",
  "The dark is older than the stone.",
  "The dark gives nothing it was not given.",
  "The dark is a patient student.",
  "The dark forgets nothing.",
  "The dark has weight and preference.",
  "The dark prefers the silent ones.",
  "The dark takes the interested first.",
  "The dark has a habit of listening.",
  "The dark follows you only sometimes.",
  "The dark has texture, and you can feel it.",
  "The dark will not meet your eye.",
  "The dark smells faintly of iron.",
  "The dark has a temperature.",
  "The dark is not an absence. It is a presence.",
  "The dark has memory. Long memory.",
  "The dark is where the walls whisper to each other.",
  "The dark does not hate you. That is worse.",
  "The dark is indifferent and thorough.",
  "The dark presses gently. Then firmly.",
  "The dark watches you adjust.",
  "The dark has a sense of humor. Small. Cold.",
  "The dark wants you to go deeper.",
  "The dark learns your name in syllables.",
  "The dark has been here longer than anything.",
  "The dark wears the architecture like a glove.",
  "The dark has a throat and uses it.",
  "The dark does not need the dungeon. The dungeon needs it.",
  "The dark fits perfectly inside your chest.",
  "The dark is not evil. Evil is too small.",
  "The dark is fluent in silence.",
  "The dark holds you loosely.",
  "The dark is where time finds no purchase.",
  "The dark is what remains.",
  "The dark is the only ground below.",
  "The dark is a long sentence. Still speaking.",
  "The dark has a second mouth for the brave.",
  "The dark is tired of being patient.",

  // ── Batch 14: Biological Horror ──
  "Something has molted here recently.",
  "Wet trails climb the wall out of reach.",
  "A nest, warm, abandoned hours ago.",
  "The fungus breathes when you do not.",
  "Eggs in a cluster, translucent.",
  "Something shed teeth like scales.",
  "The wall pulses faintly, almost invisibly.",
  "A tongue too long for any mouth.",
  "Organs arranged in a small neat pile.",
  "The air is dense with spores.",
  "A husk shaped roughly like you.",
  "The moss has patterns of eyes.",
  "Something dragged itself and left a stain.",
  "A bloom of pale flesh on cold stone.",
  "Tendrils retract when the light moves.",
  "A ribcage open like a cupboard.",
  "Veins in the floor. Not yours.",
  "The bone is warm where you touch it.",
  "Something keeps time with your pulse.",
  "A nest of hair, still growing.",
  "The walls have pores. They breathe.",
  "Bile stains in a ring around the room.",
  "Teeth grow between the stones.",
  "Something beneath the flagstones beats.",
  "Fresh skin shed in a single curl.",
  "The mold forms sentences in unfamiliar script.",
  "A spine propped upright. Too many vertebrae.",
  "Hair grows from a crack in the stone.",
  "A heart, dry, pinned to the wall.",
  "The pool has skin.",
  "A calcified palm in the masonry.",
  "Mandibles you cannot guess the owner of.",
  "The floor breathes when you stand still.",
  "An eye embedded in a pillar, blinking.",
  "Something ate, then chose not to leave.",
  "The corpse has not finished changing.",
  "A sac of fluid where the ceiling sags.",
  "The rot has a preferred direction.",
  "Digestive fluids. Not yours, not an animal's.",
  "Something pupates behind the wall.",

  // ── Batch 4: Weapons of the fallen, dead gods ──
  "The torch remembers nothing.",
  "Something breathes behind the wall.",
  "Your map ends here.",
  "The stone is always wet.",
  "No echo returns.",
  "A sword, no hand to hold it.",
  "The gods have other concerns.",
  "Bones ground to dust by boots.",
  "The air tastes of old iron.",
  "Whatever prayed here was not heard.",
  "The compass needle cannot decide.",
  "Armor split at the seam.",
  "The altar holds nothing sacred now.",
  "Your footsteps sound like someone else.",
  "A helmet, visor facing down.",
  "No name carved on this grave.",
  "The dark is patient.",
  "Wet earth, fresh displacement.",
  "This passage was not here before.",
  "A lantern, still warm.",
  "The chain leads nowhere useful.",
  "Ribs spread open like a book.",
  "The shrine was not abandoned gently.",
  "Something learned your rhythm.",
  "The ceiling is lower than before.",
  "Prayers worn into stone by fingers.",
  "The wound in the wall seeps.",
  "A shield, dented from within.",
  "The rot has tenure here.",
  "Scuttling, then silence, then scuttling.",
  "The north means nothing underground.",
  "Candle wax, no candle.",
  "Someone scratched a warning, then stopped.",
  "The second staircase descends further.",
  "A gauntlet, palm up, empty.",
  "The sound arrives before the cause.",
  "This god stopped answering long ago.",
  "The floor is softer than stone.",
  "The lock is on the wrong side.",
  "Spores, not dust.",
  "A cloak, still holding a shape.",
  "The dark folds in on itself.",
  "Three passages, all familiar.",
  "The well has no bottom sound.",
  "Your shadow leans the wrong way.",
  "Blood older than memory.",
  "Teeth marks on the torch handle.",
  "The inscription ends mid-sentence.",
  "A boot, one boot.",
  "The fungus glows without warmth.",
  "Something has been counting the days.",
  "The walls remember pressure.",
  "An offering, rejected and left.",
  "You breathe slower without knowing.",
  "Something feeds on the quiet.",
  "Calcified hands still gripping stone.",
  "The idol's face has been removed.",
  "Your light reaches less than before.",
  "A crossbow, bolt still loaded.",
  "The corridor lists to the left.",
  "Water comes through but does not leave.",
  "The smell changes before the creature.",
  "The passage remembers the flood.",
  "A body positioned like it chose this.",
  "Rust the color of old wounds.",
  "Whatever lived here did not leave.",
  "The next room sounds the same.",
  "A dagger in the floor.",
  "The silence has texture now.",
];

// Ticker idle phrases - shown in the single-line readout while Codex
// is spinning up, before any real tool-call data arrives. Gothic, terse.
// The ticker swaps to real stream data the moment it arrives.
export const TICKER_IDLE_MESSAGES = [
  "Listening for footsteps in the walls.",
  "The scrying glass has not cleared.",
  "The raven circles. It has not landed.",
  "The sigils take their time to warm.",
  "The candle gutters, then holds.",
  "Something stirs behind the lock.",
  "The compass spins, then settles south.",
  "Runes glow faint against wet stone.",
  "The thread is drawn. Not yet cut.",
  "Ink pools. The pen has not moved.",
  "The pact is being read.",
  "The bones are cooling.",
  "The ritual circle draws itself.",
  "Incense rises and does not fall.",
  "The names are being counted.",
  "The door is thinking.",
  "Smoke gathers at the ceiling first.",
  "The scale balances, then tips.",
  "The mirror is nearly ready to show.",
  "The dark is taking its measure.",
  "Old iron remembers its shape.",
  "The grimoire opens to its own page.",
  "Wax seals soften in the heat.",
  "The summoning has been heard.",
  "Breath held. Not yet released.",
];

// Phrases shown when the audit genuinely returns nothing - gothic
// replacement for \"No issues could be retrieved.\" tech-speak.
export const TICKER_FAILURE_MESSAGES = [
  "The oracle refused to speak.",
  "No shadow rose to meet you.",
  "The bones rolled blank.",
  "The dungeon holds its tongue.",
  "The scrying glass showed only your face.",
  "No demons answered the summons.",
  "The grimoire snapped shut.",
  "The ritual circle broke without finishing.",
  "The dark returned an empty ledger.",
  "Silence, and then more silence.",
  "The raven did not return.",
  "The pact was not honored tonight.",
  "The signal was swallowed whole.",
  "Nothing rose to be named.",
];

// Log line (Guild Ledger) replacement for tech-y "No data received"
export const LEDGER_FAILURE_MESSAGES = [
  "The thread goes slack.",
  "The echo returns empty.",
  "The summoning fails silently.",
  "The dark offers nothing.",
  "The oracle withholds.",
  "The pact is severed.",
];

// Messages shown when a demon is first encountered in battle
export const ENCOUNTER_MESSAGES = [
  "It reeks of rot.",
  "This one's fast.",
  "Teeth. Too many teeth.",
  "It was waiting.",
  "Stand your ground.",
  "Ugly thing.",
  "It doesn't blink.",
  "Wrong turn.",
  "Big. Angry.",
  "Eyes in the dark.",
  "It heard you coming.",
  "The stench hits first.",
  "Older than the dungeon.",
  "It unfolds from the wall.",
  "Not dead. Never was.",
  "The ground shakes beneath it.",
  "It remembers your kind.",
  "Too close to run.",
  "The dark parts around it.",
  "It doesn't need to breathe.",
  "Cornered. Both of you.",
  "Its patience ends now.",
  "The torch flickers near it.",
  "Bone and sinew. Nothing else.",
  "It smiles without a mouth.",
];

// Messages shown after defeating a demon
export const VICTORY_MESSAGES = [
  "It's done.",
  "One less.",
  "The blood dries quick.",
  "Won't miss that one.",
  "Still standing.",
  "Barely.",
  "On to the next.",
  "It stayed down.",
  "Good riddance.",
  "Wounds heal. Move on.",
  "The dark feels lighter.",
  "The stench remains.",
  "It fell apart slowly.",
  "Silence returns.",
  "Not pretty. But done.",
  "The blade held.",
  "One fewer shadow.",
  "It did not die quietly.",
  "The floor drinks what's left.",
  "Press on.",
  "You're still bleeding.",
  "That was close.",
  "Mark the wall. Move on.",
  "The echoes settle.",
  "Better it than you.",
];

// Messages for the dungeon hall (shown as subtitle/flavor)
// ~260 entries - players browse for a while, so variety matters.
// Tone: dark, cold, terse. Gothic. The hall as a gallery of horrors
// waiting to be faced one at a time.
export const HALL_MESSAGES = [
  // ── Original ──
  "They're all waiting.",
  "Pick your kill.",
  "So many.",
  "One at a time.",
  "The hall reeks of them.",
  "Choose wisely.",
  "The worst ones hide at the top.",
  "They know your name.",
  "Each one worse than the last.",
  "The dungeon does not empty easily.",

  // ── The Collective ──
  "A menagerie of grievances.",
  "They gathered while you climbed.",
  "Each a wound the site cannot close.",
  "They feed on neglect.",
  "The room is full. The room was always full.",
  "Some were born here. Some crawled in.",
  "They share a hunger.",
  "A congress of small cruelties.",
  "They whisper each other's names.",
  "A parliament of failures.",
  "They grew in the silence.",
  "Many are one. One is many.",
  "They are a pattern.",
  "A choir with no melody.",
  "They breed in inattention.",
  "A long line of old wrongs.",
  "The hall holds more than it should.",
  "They are the arrears.",
  "A crowd with no leader and no end.",
  "Each learned from the last.",
  "They came from your own hand.",
  "Some you caused. Some you allowed.",
  "A family portrait, crooked.",

  // ── The Act of Choosing ──
  "Decide.",
  "First blood is yours to choose.",
  "No order is the right order.",
  "Pick what you can afford to face.",
  "The brave choose the largest. The wise choose otherwise.",
  "Start where it hurts least.",
  "Start where it hurts most.",
  "Choose. They are patient.",
  "There is no wrong choice. Only delay.",
  "Every demon has a first turn.",
  "The order matters. The order never matters.",
  "Point at the one you fear.",
  "Name one and approach.",
  "The list is yours to cut down.",
  "You cannot refuse all of them.",
  "Tally them as you go.",
  "Every scroll counts.",
  "Even small ones bite.",
  "Count them. Choose.",
  "Your blade does not pick itself.",
  "Do not think too long.",
  "They notice hesitation.",

  // ── They Watch ──
  "Eyes turn to you when you enter.",
  "Every eye in the room.",
  "They track you without moving.",
  "You feel seen.",
  "Their attention is a weight.",
  "They learned your gait already.",
  "They heard you breathing from outside.",
  "None of them blink.",
  "Their heads follow you.",
  "They have studied you from the list.",
  "You are not a stranger here.",
  "They know which hand holds the blade.",
  "They have seen your kind.",
  "They have seen you, specifically.",
  "They remember the last one to stand there.",
  "You are on display too.",
  "You are in their hall, not yours.",
  "They count your breaths.",
  "Their stillness is a measurement.",
  "You have been appraised.",

  // ── Sound and Silence ──
  "Breath, not quite yours.",
  "Claws on stone, somewhere.",
  "Something drags and stops.",
  "A sigh from the wall.",
  "The hush is contagious.",
  "Silence with a heart in it.",
  "A skitter. Then nothing.",
  "A wet sound, far off.",
  "The hum of many held breaths.",
  "A low growl, unclaimed.",
  "Chains settle when you pass.",
  "The torches say nothing.",
  "No echoes answer your footstep.",
  "Something clicks. Then clicks again.",
  "The silence is alert.",
  "Your heartbeat is louder than the hall.",
  "A whisper between two stones.",
  "The quiet has weight.",
  "Something hums at a pitch you cannot place.",
  "A cough from the shadows.",

  // ── Individual Demons ──
  "That one bleeds when it's not cut.",
  "This one was small once.",
  "The tall one has been here longest.",
  "The low one eats by waiting.",
  "That one wears the last champion's ring.",
  "This one is not as asleep as it looks.",
  "The old ones are quiet.",
  "The young ones are hungry.",
  "Some hide behind larger siblings.",
  "One has no name and prefers it.",
  "The crooked one remembers.",
  "That one took three to put down last.",
  "The thin one is faster than it seems.",
  "The fat one does not need to be fast.",
  "One is already wounded. Good.",
  "One looks kind. It isn't.",
  "That one learned from the last attempt.",
  "The pale one has done this before.",
  "The red one will not go quietly.",
  "The twin is worse than the first.",

  // ── The Hall as Place ──
  "The arches stretch farther than they should.",
  "The stone remembers every visitor.",
  "The floor has been swept. Recently.",
  "The walls are warm where they should be cold.",
  "The sconces burn without oil.",
  "The ceiling is the color of old breath.",
  "The tiles are fresh. The mortar is fresh.",
  "Nothing here has dust.",
  "Everything here has dust.",
  "The air sits heavy in the room.",
  "The hall was built for this purpose.",
  "The architecture favors the adversary.",
  "There are no benches. There are no exits.",
  "The door you came through is closed now.",
  "The windows are not windows.",
  "The columns lean inward a hair.",
  "The acoustic favors screaming.",
  "The hall has seen every kind of ending.",
  "The space was shaped to trap attention.",
  "The floor is slightly warm beneath your boots.",

  // ── What Came Before ──
  "Others stood here and chose.",
  "Your predecessor was not thorough.",
  "Someone made progress. Not enough.",
  "A previous name, scratched out.",
  "They tried. They are not here.",
  "The last one started top-left.",
  "Their weapons remain. They do not.",
  "You are not the first. Rarely the last.",
  "The tally from last time is still on the wall.",
  "Boots left behind, still standing.",
  "A cloak on a peg. No owner.",
  "The rust on the weapon rack is new.",
  "One chose poorly. One chose better.",
  "The dead do not vote on your approach.",
  "You follow footsteps that end here.",
  "Their blood is still on the flagstones.",

  // ── The Weight Ahead ──
  "The work is long.",
  "None of this will be quick.",
  "Hours are your currency now.",
  "You will remember some of these.",
  "This will take what it takes.",
  "No shortcut exists.",
  "The easy ones still cost.",
  "Each one earns its own scar.",
  "The list looks longer when you start.",
  "The list looks longer when you finish.",
  "Sleep is a memory you postpone.",
  "Food is a ritual now.",
  "Mercy will not be available.",
  "The work is the path.",
  "The work is the reward.",
  "Dawn is a theory outside this hall.",
  "Time flows at whatever pace you grant it.",

  // ── The Dungeon Speaks ──
  "The hall breathes with you.",
  "The dungeon is in no hurry.",
  "The architecture approves of you.",
  "The dungeon was here first.",
  "The dungeon makes no offers.",
  "The dungeon is not your opponent. They are.",
  "The dungeon is neutral. Deeply.",
  "The dungeon keeps a count.",
  "The dungeon has many more halls.",
  "The dungeon remembers its favorites.",
  "The dungeon is indifferent to success.",
  "The dungeon will still be here tomorrow.",
  "The dungeon recognizes a returning visitor.",
  "The dungeon does not grade on effort.",

  // ── Brief Imperatives ──
  "Strike first.",
  "Strike clean.",
  "Breathe out slowly.",
  "Hold your blade lower.",
  "Watch the largest one.",
  "Watch the smallest one.",
  "Pace yourself.",
  "Do not flinch.",
  "Do not linger.",
  "Do not return.",
  "Draw.",
  "Step.",
  "Kneel for none of them.",
  "Promise them nothing.",
  "Accept no parley.",
  "Forget their names after.",
  "Leave what you cannot carry.",
  "Bury nothing.",
  "Bless nothing.",

  // ── The Adversarial Math ──
  "Subtract them.",
  "The equation is simple.",
  "Each one is a variable.",
  "You are the solution.",
  "One subtracted is one done.",
  "The remainder is the remainder.",
  "Zero is the target.",
  "Arithmetic of the blade.",
  "Each cut is a deduction.",
  "You balance the ledger.",
  "The ledger is the hall.",
  "Red ink only.",
  "They are debts called due.",

  // ── Condensations ──
  "Quiet.",
  "Thick air.",
  "Eyes, many.",
  "Only hands.",
  "One cry, far.",
  "Wet floor.",
  "Cold palm.",
  "A whisper.",
  "Small sound.",
  "Low breath.",
  "Slow blink.",
  "No birds.",
  "No wind.",
  "No clock.",

  // ── Mental State ──
  "You have been still too long.",
  "Your mind lists. Your hand chooses.",
  "You are calm. That will pass.",
  "Fear is an old friend tonight.",
  "Doubt is a luxury here.",
  "Your thoughts grow very quiet.",
  "A strange patience takes you.",
  "You feel less yourself.",
  "You feel more yourself.",
  "Something steady in your chest.",
  "The hand decides before the mind.",
  "You forget to be afraid for a moment.",
  "Focus narrows to a single row.",
  "The list simplifies itself.",
  "You become economical.",

  // ── Specific Observations ──
  "One is chained. The chain is new.",
  "One bleeds from no visible wound.",
  "One has its back to you.",
  "One is smiling without a mouth.",
  "One has hands where eyes should be.",
  "One is pacing in a small circle.",
  "One is standing on the last champion's cloak.",
  "One is older than the hall.",
  "One is whispering to itself.",
  "One is not the same from different angles.",
  "One has been scratched deep.",
  "One is missing pieces of itself.",
  "One has your face. A little.",

  // ── Warnings in the Hall ──
  "Do not feed them.",
  "Do not meet their gaze for long.",
  "Do not count them out loud.",
  "Do not turn your back.",
  "Do not speak their names until you must.",
  "Do not ask them questions.",
  "Do not accept what they offer.",
  "Do not pity any of them.",
  "Do not count on mercy.",
  "Do not assume the small ones are small.",

  // ── Closing Beats ──
  "Begin.",
  "Step forward.",
  "Choose. And then choose again.",
  "The hall waits as long as you need.",
  "The hall does not wait forever.",
  "What you do here will be counted.",
  "This is where the work happens.",
  "Raise the blade.",
  "Raise your name.",
  "Start.",
];
